services:
  web:
    build:
      context: .
      target: development
    restart: on-failure
    command: >
      sh -c "./manage.py migrate &&
      ./manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app
    environment:
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
      POETRY_CACHE_DIR: /app/.quera/cache/poetry
    env_file:
      - .env
    ports:
      - 8080:8080
    logging:
      driver: local
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: